# In this notebook, we will cover some fundamentals of tensor using TensorFlow

More Specially, we 're going cover :
* Intro to tensor
* Getting info from tensors
* Manipulating tensors (change value in tensors)
* Tensors & Numpy
* Using @tf.function which is a way to spped up ur regular pytong Function
* Using GPUs with TensorFlow (ot TPUs)

In [1]:
import tensorflow as tf
tf.__version__

'2.12.0'

### Creating with `tf.constant()`

In [2]:
# create tensor scaler
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# create tensor vector (check diff)
vec_2 = tf.constant([1, 2])
print(vec_2.ndim)
vec = tf.constant([1, 2], shape=(2,1))
print(vec.ndim)

1
2


In [4]:
# create tensor matrix
mat = tf.constant([[1, 2],
                     [3, 4],
                     [5, 6]], dtype=tf.int16)
mat

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

### Creating with `tf.variable`

In [5]:
# create tensor scaler
scaler_2 = tf.Variable(7)
scaler_2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>

In [6]:
# create tensor vec
changable_vec = tf.Variable([1, 2, 3])
unchangable_vec = tf.constant([1, 2, 3])
changable_vec, unchangable_vec

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>)

In [7]:
# Try Change Values in it
changable_vec[1].assign(7)
changable_vec

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 7, 3], dtype=int32)>

### Creating Randoms tensors `tf.random`

In [8]:
# create Random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.uniform(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2), mean=2, stddev=1)
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1.2434196 , 1.931453  ],
        [2.0759501 , 0.7426156 ],
        [1.7680624 , 0.18921447]], dtype=float32)>)

### Let's, shuffle tensors with `tf.shuffle`

In [9]:
# Shuffle tensor
random_1  = tf.random.Generator.from_seed(42)
random_1  = random_1.uniform(shape=(3,2))
shuffle_1 = tf.random.shuffle(random_1)
random_1, shuffle_1


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.45230794, 0.49039817],
        [0.7493447 , 0.73561966],
        [0.1889317 , 0.52027524]], dtype=float32)>)

In [10]:
# Shuffle with specific seed
tf.random.set_seed(42)
shuffle_1 = tf.random.shuffle(random_1)
shuffle_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.45230794, 0.49039817],
       [0.1889317 , 0.52027524],
       [0.7493447 , 0.73561966]], dtype=float32)>

In [11]:
# creating tenosrs with ones or zeros
tensors_zeros = tf.zeros(shape=(3,3))
tensors_ones = tf.ones(shape=(3,4))
tensors_zeros, tensors_ones

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>)

### Getting information from tensors
* shape
* rank
* size
* nidm


In [12]:
# create tenosrs
tensors_info_2 = tf.random.Generator.from_seed(42)
tensors_info_2 = tensors_info_2.uniform(minval=0, maxval=2, shape=(3,4))
tensors_info_2

# Getting info
tensors_info_2, tensors_info_2.shape, tf.size(tensors_info_2), tensors_info_2.ndim, tensors_info_2.dtype

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1.4986894 , 1.4712393 , 0.9046159 , 0.98079634],
        [0.3778634 , 1.0405505 , 1.7473762 , 0.93843436],
        [1.2786517 , 1.2934234 , 1.9249351 , 0.8201833 ]], dtype=float32)>,
 TensorShape([3, 4]),
 <tf.Tensor: shape=(), dtype=int32, numpy=12>,
 2,
 tf.float32)

### Expanding tensors with axis
* Method 1
* Method 2

In [13]:
# Method_1
tensors_info_3 = tensors_info_2[:, tf.newaxis, :]
tensors_info_3

<tf.Tensor: shape=(3, 1, 4), dtype=float32, numpy=
array([[[1.4986894 , 1.4712393 , 0.9046159 , 0.98079634]],

       [[0.3778634 , 1.0405505 , 1.7473762 , 0.93843436]],

       [[1.2786517 , 1.2934234 , 1.9249351 , 0.8201833 ]]], dtype=float32)>

In [14]:
# Method_2
tensors_info_3 = tf.expand_dims(tensors_info_2, axis=0)
tensors_info_3

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1.4986894 , 1.4712393 , 0.9046159 , 0.98079634],
        [0.3778634 , 1.0405505 , 1.7473762 , 0.93843436],
        [1.2786517 , 1.2934234 , 1.9249351 , 0.8201833 ]]], dtype=float32)>

### Manuplating Tensors
* basic operations
** add
** sub
** mul
** div

All of that in section `tf.math` of doc

In [15]:
# create Tenosrs
tenors_1 = tf.random.uniform(shape=(3,4))
tenors_2 = tf.random.uniform(shape=(3,4))

# add
tensors_add = tf.add(tenors_1, tenors_2)
# sub
tensors_sub = tf.subtract(tenors_1, tenors_2)
# Mul
tensors_mul = tf.multiply(tenors_1, tenors_2)
tenors_1, tenors_2, tensors_add, tensors_sub, tensors_mul


(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , 0.252187  ],
        [0.73115396, 0.89256823, 0.94674826, 0.7493341 ],
        [0.34925628, 0.54718256, 0.26160395, 0.69734323]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, 0.3431449 ],
        [0.51063764, 0.3777541 , 0.07321596, 0.02137029],
        [0.2871771 , 0.4710616 , 0.6936141 , 0.07321334]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1.4292591 , 1.1130251 , 0.94837904, 0.5953319 ],
        [1.2417916 , 1.2703223 , 1.0199642 , 0.7707044 ],
        [0.63643336, 1.0182441 , 0.9552181 , 0.77055657]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.05347657, -0.1440674 ,  0.91360974, -0.09095788],
        [ 0.22051632,  0.51481414,  0.8735323 ,  0.7279638 ],
        [ 0.06207919,  0.07612097, -0.43201017,  0.6241299 ]],
       dtype=float32)>,
 <tf.Tensor: shap

In [16]:
# create Tenosrs
tenors_1 = tf.random.uniform(shape=(3,4))
tenors_2 = tf.random.uniform(shape=(3,4))
# maltiply
tensors_multiply = tf.multiply(tenors_1, tenors_2)
# matmul
tensors_matmul = tf.matmul(tenors_1, tf.transpose(tenors_2))
tensors_multiply, tensors_matmul

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0.5945208 , 0.16893664, 0.21093033, 0.40862048],
        [0.18673667, 0.07757433, 0.40119007, 0.19143409],
        [0.01307266, 0.7515452 , 0.6018002 , 0.06797213]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1.3830082 , 1.0210729 , 0.932799  ],
        [1.3104545 , 0.85693514, 1.0949793 ],
        [1.2171063 , 0.8678542 , 1.4343902 ]], dtype=float32)>)

In [17]:
# dot product
tf.tensordot(tenors_1, tf.transpose(tenors_2), axes=1)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.3830082 , 1.0210729 , 0.932799  ],
       [1.3104545 , 0.85693514, 1.0949793 ],
       [1.2171063 , 0.8678542 , 1.4343902 ]], dtype=float32)>

### Change DataTypes Of Tensors Using `tf.cast()`


In [26]:
# create tensor
tensor_np = tf.constant(tf.range(0, 12), shape=(4,3))
print(f"First Type is : {tensor_np.dtype}")
tensor_np = tf.cast(tensor_np, dtype=tf.float16)
print(f"Second Type is : {tensor_np.dtype}")
tensor_np

First Type is : <dtype: 'int32'>
Second Type is : <dtype: 'float16'>


<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float16)>

### Some Aggregation With Tensors `tf.reduce_...`

In [64]:
import numpy as np

tf.random.set_seed(42)
our_tensor   = tf.constant(np.random.randint(0, 14, size = 12 ), shape = (3,4))
our_tensor_2 = tf.random.uniform(shape=(3,4) ,minval= 0, maxval= 12, dtype=tf.int32)
our_tensor_2


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[7, 5, 5, 6],
       [4, 8, 7, 7],
       [7, 3, 4, 4]], dtype=int32)>

In [60]:
# get min
tf.reduce_min(our_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [61]:
# get max
tf.reduce_max(our_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=11>

In [62]:
# get mean
tf.reduce_mean(our_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [63]:
# get sum
tf.reduce_sum(our_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=59>

### Get variance & standard deviation with `tensorflow_probability` module

In [65]:
# import Tensorflow Probabilty
import tensorflow_probability as tfp

In [69]:
# get variance
tfp.stats.variance(our_tensor_2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 1, 2], dtype=int32)>

In [71]:
# get variance
tfp.stats.stddev(tf.cast(our_tensor_2, dtype=tf.float32))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.4142135, 2.0548046, 1.2472191, 1.2472191], dtype=float32)>

### get postions of max and min `tf.argmax()` and `tf.argmin()`

In [87]:
# create tensor
tf.random.set_seed(30)
tenosr_operations = tf.constant(tf.random.uniform(minval=0, maxval=12, shape=[2,6], dtype=tf.int32))
tenosr_operations

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 3,  1,  7,  4,  8,  0],
       [10,  6, 11,  5,  0,  7]], dtype=int32)>

In [88]:
# get max index
tf.argmax(tenosr_operations), tf.reduce_max(tenosr_operations)

(<tf.Tensor: shape=(6,), dtype=int64, numpy=array([1, 1, 1, 1, 0, 1])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=11>)

In [85]:
# get max index
tf.argmin(tenosr_operations), tf.reduce_min(tenosr_operations)

(<tf.Tensor: shape=(), dtype=int64, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>)